name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: [".", "v2"]
        defaults:
            run:
              working-directory: ${{ matrix.package }}
        steps:
            -   name: Set up Go 1.15
                uses: actions/setup-go@v2
                with:
                    go-version: ^1.15

            -   name: Check out
                uses: actions/checkout@v2

            -   name: Get dependencies
                run: go get -v ./...

            -   name: Enforce Go Formatted Code
                run: "! go fmt ./... 2>&1 | read"

            -   name: Identify Vet Errors
                run: go vet ./...

            -   name: Build
                run: go build ./...

            -   name: Test
                run: go test -race -v ./...

            -   name: CI fail
                if: ${{ failure() }}
                run: |
                    curl --request POST '${{ secrets.WEBHOOK_URL }}' \
                    --data-raw '${{ 
                        format('{{"text": "{0}"}}', 
                            format('Commit: {0}/commit/{1}<br>Branch: {2}<br>Repository: {0}<br>Workflow URL: {0}/actions/runs/{3}', 
                                format('https://github.com/{0}', github.repository), 
                                github.sha, 
                                github.ref, 
                                github.run_id
                            )
                        ) 
                    }}'